name: CMake

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Install Docker
    run: sudo apt install runc containerd docker.io

  - name: Run Docker
    run: |
       docker run -it -v "$(pwd)/logs/:/home/logs/" logger && \
       ls "$(pwd)/logs/:/home/logs/" 


  - name: Upload Artifact
    uses: actions/upload-artifact@v2
    with:
        name: executable
        path: ${{github.workspace}}
